### ISSUE TITLE
1.4 version of heads keeps crashing

### ISSUE THREAD

**Issue by FrostKnight** [Nitrokey/heads#13]
I have never had a crash issue, with the previous version of heads, on my nitropad T430i
but the moment I upgraded, yeah... things went bad, it keeps crashing after less than 20 minutes of usage. No idea why...

It happens when I am within my operating system on it, so I don't see what is going on beneath it, aka, no real signs of errors, etc...

Am I missing something? 

Feel free to respond, I don't have a clue lol.

**Comment by szszszsz** [comment]
Can you tell which binary did you use for the update?

**Comment by FrostKnight** [comment]
@szszszszsz
I responded on the forum twice, but I figured I should say, qubesos has problems with i7-3632QM as you guys have said, maybe in the 1.4.0 version, the .npf patch for that version when used has problems with that processor and the intel me gets deleted instead of disabled for that cpu.

Just a guess...

;)

**Comment by tlaurion** [comment]
@szszszsz
