### ISSUE TITLE
documentation on switching to heads, desired

### ISSUE THREAD

**Issue by FrostKnight** [Nitrokey/heads#22]
How would I go about, changing a thinkpad from coreboot to nitrokey heads?

Like say, do I, do this?:

flashrom -p internal -w top.rom 
flashrom -p internal -w bottom.rom

For X230, or T430, etc...

**Comment by FrostKnight** [comment]
So this rom would be needed? I assume this is the full rom:
 https://github.com/Nitrokey/heads/releases/download/v1.4/nitropad-x230-maximized-v1.4.rom

This will work under 2 conditions:

If nitrokey heads bios isn't already on it?

And,  if its not determined to be locked when I use flashrom -p internal

Yes?

**Comment by FrostKnight** [comment]
Would i do it this way:
flashrom -p internal -w nitropad-x230-maximized-v1.4.rom

And then reboot?

**Comment by tlaurion** [comment]
@szszszsz ?

**Comment by daringer** [comment]
> Would i do it this way: flashrom -p internal -w nitropad-x230-maximized-v1.4.rom
> 
> And then reboot?

In theory yes, you might also want to use the more recent roms - but from our experience most of the devices have a locked flash, thus I assume you'll need an external flashing device to do the migration - we also offer this as a service.

closing for now, please re-open if needed
