### ISSUE TITLE
[nitropad-nx] watchdog-based poweroff/reboot not triggered correctly

### ISSUE THREAD

**Issue by daringer** [Nitrokey/heads#24]
```
if [ "${CONFIG_BOARD%_*}" = nitropad-nv41 || "${CONFIG_BOARD%_*}" = nitropad-ns51 ]; then
```

should be:

```
if [ "${CONFIG_BOARD%_*}" = nitropad ]; then
```

**Comment by tlaurion** [comment]
There is no board config named ns51. @daringer is this fixed with your own suggestion?

**Comment by tlaurion** [comment]
> There is no board config named ns51. Only nv41/ns50
> 
>  @daringer is this fixed with your own suggestion? 

https://github.com/linuxboot/heads/blob/master/initrd/bin/reboot#L21

Not fixed under master.
PR expected.

**Comment by daringer** [comment]
fixed with: https://github.com/Nitrokey/heads/commit/302fe741697a312955faf4ec888cf0d179084ce6
