### ISSUE TITLE
ns50 v2.3 boots to blank screen

### ISSUE THREAD

**Issue by commandline-be** [Nitrokey/heads#28]
### A. Provide Hardware Details

**1. What board are you using (see list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))?**

**2. Does your computer have a dGPU or is it iGPU-only?**
- [ ] dGPU
- [x] iGPU-only

**3. Who installed Heads on this computer?**
- [ ] Insurgo
- [x] Nitrokey
- [ ] Purism
- [ ] Other provider
- [ ] Self-installed

**4. What PGP key is being used?**
- [ ] Librem Key
- [ ] Nitrokey Pro 2
- [x] Nitrokey Storage
- [ ] Yubikey
- [ ] Other

**5. Are you using the PGP key to provide HOTP verification?**
- [x] Yes
- [ ] No
- [ ] I don't know

### B. Identify how the board was flashed

**1. Is this problem related to updating heads or flashing it for the first time?**
- [ ] First-time flash
- [x] Updating heads 

**2. If the problem is related to an update, how did you attempt to apply the update?**
- [x] Using the Heads GUI
- [ ] Flashrom via the Recovery Shell
- [ ] External flashing

**3. How was Heads initially flashed**
- [ ] External flashing
- [x] Internal-only / 1vyrain
- [ ] Don't know

**4. Was the board flashed with a maximized or non-maximized/legacy rom?**
- [ ] Maximized
- [x] Non-maximized / legacy
- [ ] I don't know

**5. If Heads was externally flashed, was IFD unlocked?**
- [ ] Yes
- [ ] No
- [x] Don't know

### C. Identify the rom related to this bug report

**1. Did you download or build the rom at issue in this bug report?**
- [x] I downloaded it
- [ ] I built it

**2. If you downloaded your rom, where did you get it from?**
- [ ] Heads CircleCi
- [ ] Purism
- [x] Nitrokey
- [ ] Somewhere else (please identify)

*Please provide the release number or otherwise identify the rom downloaded*

**3. If you built your rom, which repository:branch did you use?**
- [ ] Heads:Master
- [ ] Other (please identify)

**4. What version of coreboot did you use in building?**
- [ ] 4.8.1 (current default in heads:master)
- [ ] 4.13
- [ ] 4.14
- [ ] 4.15
- [ ] Other (please specify)
- [] I don't know

**5. In building the rom where did you get the blobs?**
- [] No blobs required
- [ ] Provided by the company that installed Heads on the device
- [ ] Extracted from a backup rom taken from this device
- [ ] Extracted from another backup rom taken from another device (please identify the board model)
- [ ] Extracted from the online bios using the automated tools provided in Heads
- [ ] I don't know

## Please describe the problem

**Describe the bug**

After boot there is  black screen, assumed to be because intel_iommu=igfx_off is still in place.
Attempts to manual boot using kexec-boot -b /boot -e 'kernel /boot/vmlinuz|initrd /boot/initrd.img|....' resulted in fail.

**To Reproduce**

**Expected behavior**

Normal boot process requesting LUKS password

**Screenshots**

**Additional context**

**Comment by commandline-be** [comment]
Obviously confirmed to be because of not changing `intel_iommu=igfx_off` to `intel_iommu=on` before updating firmware.

A simple procedure when not preparing to update by adjusting grub.cfg to replace igfx_off with on

1. choose to exit to recovery shell
2. remount /boot as writable ( `mount -o remount,rw /boot` )
3. replace igfx_off with on for all intel_iommu= keys
4. save the file
5. sign the bootloader ( `kexec-sign-config -p /boot`  ) note this requires the user pin
6. reboot by typing `reboot`
7. confirm to sign the modified grub.cfg , note this also requires the user pin
8. you should now see the luks prompt again

this worked for me

**Comment by commandline-be** [comment]
I can also confirm this does indeed appears to greatly affect the CPU rapidly heating up. There is barely any change now.

It is unclear what drivers work best with the ns50 iGPU.   /boot/grub/grub.cfg`
After reboot it reports use of i915 and Mesa Intel Graphics (ADL GT2)

Don' forget to enable hardware acceleration in the browser.

**Comment by commandline-be** [comment]
it is unknown at this time if `nomodeset` is preferable to keep or it can be removed from the kernel boot parameters

**Comment by tlaurion** [comment]
@daringer that was https://github.com/linuxboot/heads/pull/1522 related.

**Comment by commandline-be** [comment]
Thanks for the informative update. I don't know what you mean with use of KERNEL_REMOVE, this is new to me.

Thus far I've noticed repeat issues with dual screen not being detected and suspend not working, the system appears frozen.

**Comment by tlaurion** [comment]
https://github.com/Nitrokey/heads/blob/nitropad/boards/nitropad-nv41/nitropad-nv41.config#L42

**Comment by daringer** [comment]
@commandline-be thanks for testing, we'll switch the v2.3 to pre-release until we release a cleaner 2.4 version which is more consistent with the upstream state ...

**Comment by tlaurion** [comment]
https://github.com/linuxboot/heads/pull/1522#issuecomment-1821383858

**Comment by commandline-be** [comment]
@tlaurion @daringer are the references i shared (archlinux and freedesktop) of any relevance, i'm curious if compiling in the suggested patch is of any use.

right now I'm leaving the laptop with acpi_osi=Linux set as boot parameter to see if this makes a difference at all

another thing is Ubuntu Gnome reports use of Mesa while i assume this is not what i915 is about, this may require a configuration adjustment as well, is this correct ?

**Comment by tlaurion** [comment]
@commandline-be a patch for efi was missing under 2.3. Please see PR under heads for testing but only do so if you have way of flashing externally as this might break console and display.

**Comment by commandline-be** [comment]
not having had time to read thru all of #1522
unless I'm deluding myself, for me it appears gfx to be working since CPU load is remarkably lower
modifying intel_iommu value to 'on' works around the blank screen (as per normal use requirement)
the acpi_osi=Linux command-line parameter may be working, i'll know in the morning for sure

**Comment by tlaurion** [comment]
> @tlaurion @daringer are the references i shared (archlinux and freedesktop) of any relevance, i'm curious if compiling in the suggested patch is of any use.
> 
> right now I'm leaving the laptop with acpi_osi=Linux set as boot parameter to see if this makes a difference at all
> 
> another thing is Ubuntu Gnome reports use of Mesa while i assume this is not what i915 is about, this may require a configuration adjustment as well, is this correct ?


I checked real quick but again, suspend is supposed to be patched for NV41 under coreboot, not the same story is possible for NS50.

On graphical issues, if the firmware doesn't mess anything from the firmware side, the os should be able to deal with the graphic adapter as if he was the first one initializing it. Gop blob should provide the bare minimal for coreboot to  provide tables required by efifb to use the framebuffer without 3d init and make heads just draw in 2d to that FB correctly. In theory.

After that, just for all other Intel basedboards under heads, kexec to final os should be able to have i915+drm do the right thing without quirks. But that is to be tested and validated. 2.3 never offered the proper coreboot base to do proper tests, I have no idea what happened there and I'm sorry for the confusion.

**Comment by commandline-be** [comment]
for now i think it is safe to say for the NS50 `acpi_osi=Linux` works fine to remedy any suspend issues i had thus far
personally i don't mind a list of command-line boot parameters as long as 'stuff' just works

more testing tomorrow morning

**Comment by tlaurion** [comment]
> for now i think it is safe to say for the NS50 acpi_osi=Linux works fine to remedy any suspend issues i had thus far\npersonally i don't mind a list of command-line boot parameters as long as 'stuff' just works\n\nmore testing tomorrow morning

And that is where KERNEL_ADD should be used to add things required per board configurations without needing users to punch them in under grub after installation.

**Comment by commandline-be** [comment]
let's call 2.3 a beta release and add a simple script to modify /etc/default/grub to do the dirty work ?
if it works it works, if people get some acceleration and less heat on CPU that will be much appreciated already

**Comment by tlaurion** [comment]
Get me right. 2.2 to have become 2.3 would have required kernel_remove statements in kernel config if I understand well.

2.3 is faking efifb usage as of now and is actually not using it, not being feature ready.

I'm not part of the release team here, but both 2.2 and 2.3 are having issues dealing correctly with proper parameters to properly do what is supposed to be done.

2.2.1 could fix i915 parameters to boot into final os correctly, applying mitigation to release roms while fixing things correctly to create a 2.4 release actually enforcing efifb. 

As of now, anybody trying to boot other OSes, for example tinycore would fail miserably on both releases, requiring an unaccelerated FB without implying i915+drm.

If resource are scarce, it's about doing something that works minimally and then work up to max performance at this point.

In 2.2. 1 as said upstream, someone would need to apply revert of purism branch moving away to efifb to have something that works with acceleration on nv41/n50 with proper tweaks you seem to have discovered to fix suspend issues, directly passed to final os through kernel_add/kernel_remove per board config and making sure heads i915 kernel parameters matches the requirements that needed a lot of work to figure out.

That would be a working 2.2.1 release until 2.4 is workable without needing fixes.


Taking into consideration people will run a script and understand what to do is a general error. The firmware must do the right thing tm

**Comment by commandline-be** [comment]
true, then again, I'm looking at this from a consumer point of view. 
glmark2 shows promising results which makes me happy already.

`acpi_osi=Linux` does not not work as expected i can say now with confidence 
my assumption at this time is there appears to be no issue with suspend actually but with deeper sleep states which causes a no-resume state, no matter what is tried at the keyboard

**Comment by commandline-be** [comment]
found a test: this outputs all states counting from 0, for the NS50 this counts to state4 which = C10

```
grep . /sys/devices/system/cpu/cpu0/cpuidle/state*/name
# which outputs
/sys/devices/system/cpu/cpu0/cpuidle/state0/name:POLL
.....
/sys/devices/system/cpu/cpu0/cpuidle/state4/name:C10
```

the question here is if the HEADS build has the powerstates for the NS50 supported correctly ?
pm-hibernate works as expected when executed manually, this also when setting `processor.max_cstate=5  intel_idle.max_cstate=5` Ubuntu suspend does result in a freeze however.

**Comment by tlaurion** [comment]
Nitrokey would need to switch their coreboot port and follow dasharo coreboot releases closely https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/

**Comment by commandline-be** [comment]
Hey tlaurion, thanks for sharing that link. The contents support my experience, using pm-suspend or pm-hibernate there is indeed no issue. So the issue is how Ubuntu powermanagement is set to work, which i believe works with systemd.

**Comment by commandline-be** [comment]
blank screen resolved by  changing the intel_iommu= value from igfx_off to on in /etc/default/grub then running update-grub

**Comment by tlaurion** [comment]
> Hey tlaurion, thanks for sharing that link. The contents support my experience, using pm-suspend or pm-hibernate there is indeed no issue. So the issue is how Ubuntu powermanagement is set to work, which i believe works with systemd.
> 
> the blank screen was resolved already by changing the intel_iomm= value from igfx_off to on.

Note that https://github.com/linuxboot/heads/pull/1522 is getting into the right path fixing what is needed on the efifb/i915 driver removal inside of heads and was reported working by @nestire there.
