### ISSUE TITLE
unlock passphrase doesn't work with Qubes kernel 6.6.2

### ISSUE THREAD

**Issue by duncancmt** [Nitrokey/heads#30]
This is copied over from linuxboot/heads#1545

### A. Provide Hardware Details

**1. What board are you using (see list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))?**

Novacustom NV41 (Nitrokey branded)

**2. Does your computer have a dGPU or is it iGPU-only?**
- [ ] dGPU
- [x] iGPU-only

**3. Who installed Heads on this computer?**
- [ ] Insurgo
- [x] Nitrokey
- [ ] Purism
- [ ] Other provider
- [ ] Self-installed

**4. What PGP key is being used?**
- [ ] Librem Key
- [ ] Nitrokey Pro 2
- [ ] Nitrokey Storage
- [ ] Yubikey
- [x] Other - Nitrokey 3A Mini

**5. Are you using the PGP key to provide HOTP verification?**
- [x] Yes
- [ ] No
- [ ] I don't know

### B. Identify how the board was flashed

I deleted this section because I purchased this machine from Nitrokey

### C. Identify the rom related to this bug report

**1. Did you download or build the rom at issue in this bug report?**
- [ ] I downloaded it
- [ ] I built it
- [x] System came pre-flashed

**2. If you downloaded your rom, where did you get it from?**
- [ ] Heads CircleCi
- [ ] Purism
- [x] Nitrokey
- [ ] Somewhere else (please identify)

*Please provide the release number or otherwise identify the rom downloaded*

Nitrokey heads v2.2

**3. If you built your rom, which repository:branch did you use?**
- [ ] Heads:Master
- [x] Other (please identify) [Nitrokey/heads:v2.2](https://github.com/Nitrokey/heads/releases/tag/v2.2)

**4. What version of coreboot did you use in building?**
- [ ] 4.8.1 (current default in heads:master)
- [ ] 4.13
- [ ] 4.14
- [ ] 4.15
- [ ] Other (please specify)
- [x] I don't know

**5. In building the rom where did you get the blobs?**
- [ ] No blobs required
- [ ] Provided by the company that installed Heads on the device
- [ ] Extracted from a backup rom taken from this device
- [ ] Extracted from another backup rom taken from another device (please identify the board model)
- [ ] Extracted from the online bios using the automated tools provided in Heads
- [x] I don't know

## Please describe the problem

**Describe the bug**

I did a dom0 update in Qubes and now the disk unlock passphrase doesn't work anymore. Kernel 6.5.8 works fine, but kernel 6.6.2 won't boot with the unlock passphrase, only the recovery passphrase. I presume something changed with dracut or the kernel boot process preventing concatenated cpios from overriding each other, but I have no idea how I would begin to go about debugging that.

**To Reproduce**

1. Update Qubes dom0, installing kernel 6.6.2
2. Attempt to boot using the disk unlock passphrase
3. Observe that Plymouth still prompts for the recovery passphrase
4. Observe further that in the initramfs `/etc/crypttab` has not been patched and that `/secret.key` is missing

**Expected behavior**

Booting Qubes with the disk unlock passphrase does not prompt for the recovery passphrase. Also I would expect `/etc/crypttab` to be patched and `/secret.key` to be present in the initramfs if/when it drops into the OS recovery shell.

_I apologize in advance if this should've gone in the Qubes forum._

**Comment by tlaurion** [comment]
Nitrokey disables TPM Disk unlock key in their board configurations as can be seen https://github.com/Nitrokey/heads/blob/nitropad-release-v2.2/boards%2Fnitropad-nv41%2Fnitropad-nv41.config#L50

**Comment by duncancmt** [comment]
Hmm... that's odd because I managed to get it set up with `kexec-save-key` in the recovery shell with the previous kernel, 6.5.8. Is that not supposed to work with that config flag toggled? Simply booting the old kernel makes the disk unlock key work fine. @tlaurion are you suggesting that I ought to switch to mainline Heads to pick up full support for the unlock key with kernel 6.6.2 on the NV41?

**Comment by tlaurion** [comment]
Testing this as part of PR https://github.com/linuxboot/heads/pull/1541 

Works on default install of Q4.2 RC5 on x230-maximized. 
Will see after upgrading to latest. Will update this comment.

**Comment by tlaurion** [comment]
```
user@heads-tests-deb12:~/heads$ grep -Rn DISK initrd/ | grep UNLOCK
grep: initrd/bin/kexec-select-boot:178:		[[ "$CONFIG_TPM_NO_LUKS_DISK_UNLOCK" = "y" ]] && default_text="${default_text} and boot"
initrd/bin/kexec-save-default:190:if [ "$CONFIG_TPM" = "y" ] && [ "$CONFIG_TPM_NO_LUKS_DISK_UNLOCK" != "y" ] && [ "$CONFIG_BASIC" != y ]; then
initrd/bin/kexec-save-default:191:	DEBUG "TPM is enabled and TPM_NO_LUKS_DISK_UNLOCK is not set"
initrd/etc/mtab: No such file or directory
initrd/etc/functions:86:	if [ "$CONFIG_TPM_DISK_UNLOCK_KEY" == "n" ]; then
```

If it works over NK 2.2, its a bug :)

**Comment by tlaurion** [comment]
Discussion will continue from https://github.com/linuxboot/heads/issues/1545#issuecomment-1850495995

**Comment by tlaurion** [comment]
Note that upstream issue has been opened at https://github.com/QubesOS/qubes-issues/issues/8763

**Comment by tlaurion** [comment]
Fixed. See details https://github.com/QubesOS/qubes-issues/issues/8763
