### ISSUE TITLE
Reboot from Heads not working anymore after 2.1->2.4 upgrade

### ISSUE THREAD

**Issue by UndeadDevel** [Nitrokey/heads#34]
## Please identify some basic details to help process the report
After upgrading to NK Heads 2.4 from 2.1 `reboot` from Heads doesn't work anymore (it does work from QubesOS 4.2); i.e. it neither works when I trigger it manually from recovery shell nor when the reboot is supposed to be automatically triggered during OEM factory reset. It's a relatively minor issue. Possibly related to #24.

### A. Provide Hardware Details

**1. What board are you using (see list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))?**
Nitropad NV41

**2. Does your computer have a dGPU or is it iGPU-only?**
- [ ] dGPU
- [x] iGPU-only

**3. Who installed Heads on this computer?**
- [ ] Insurgo
- [x] Nitrokey (original 2.1)
- [ ] Purism
- [ ] Other provider
- [x] Self-installed (2.4 via internal GUI upgrade function)

**4. What PGP key is being used?**
- [ ] Librem Key
- [ ] Nitrokey Pro 2
- [ ] Nitrokey Storage
- [ ] Yubikey
- [x] Other (Nitrokey 3A Mini)

**5. Are you using the PGP key to provide HOTP verification?**
- [x] Yes
- [ ] No
- [ ] I don't know

### B. Identify how the board was flashed

**1. Is this problem related to updating heads or flashing it for the first time?**
- [ ] First-time flash
- [ ] Updating heads 
- [x] Neither, separate issue with the new firmware

**2. If the problem is related to an update, how did you attempt to apply the update?**
- [x] Using the Heads GUI
- [ ] Flashrom via the Recovery Shell
- [ ] External flashing

**3. How was Heads initially flashed**
- [x] External flashing (presumably...NitroKey did it)
- [ ] Internal-only / 1vyrain
- [ ] Don't know

**4. Was the board flashed with a maximized or non-maximized/legacy rom?**
- [x] Maximized (presumably)
- [ ] Non-maximized / legacy
- [ ] I don't know

**5. If Heads was externally flashed, was IFD unlocked?**
- [x] Yes (presumably)
- [ ] No
- [ ] Don't know

### C. Identify the rom related to this bug report
NK  Heads 2.4
**1. Did you download or build the rom at issue in this bug report?**
- [x] I downloaded it
- [ ] I built it

**2. If you downloaded your rom, where did you get it from?**
- [ ] Heads CircleCi
- [ ] Purism
- [x] Nitrokey (this GitHub repo)
- [ ] Somewhere else (please identify)

*Please provide the release number or otherwise identify the rom downloaded*

**3. If you built your rom, which repository:branch did you use?**
- [ ] Heads:Master
- [ ] Other (please identify)

**4. What version of coreboot did you use in building?**
- [ ] 4.8.1 (current default in heads:master)
- [ ] 4.13
- [ ] 4.14
- [ ] 4.15
- [ ] Other (please specify)
- [ ] I don't know

**5. In building the rom where did you get the blobs?**
- [ ] No blobs required
- [ ] Provided by the company that installed Heads on the device
- [ ] Extracted from a backup rom taken from this device
- [ ] Extracted from another backup rom taken from another device (please identify the board model)
- [ ] Extracted from the online bios using the automated tools provided in Heads
- [ ] I don't know

## Please describe the problem

**Describe the bug**
`reboot` from Heads recovery shell or automated scripts doesn't work; machine shuts down without rebooting instead.

**To Reproduce**
1. Upgrade NV41 to NK Heads 2.4
2. Enter recovery shell and execute `reboot`

**Expected behavior**
reboots as before under 2.1

**Comment by daringer** [comment]
yes, this is kind of a "feature"....

in [reboot](https://github.com/Nitrokey/heads/blob/nitropad/initrd/bin/reboot) and [poweroff](https://github.com/Nitrokey/heads/blob/nitropad/initrd/bin/poweroff) the EC is used for a proper shutdown - this reduces the risk that the nitropads might need to be started more than once (this may happen after a firmware update)

So I have to admit this will be a won't fix as of now...

**Comment by UndeadDevel** [comment]
Well it's not a big deal anyway; reboot from the OS works as expected. Closing as won't fix.

**Comment by UndeadDevel** [comment]
I'll just add that while sometimes rebooting from the OS does work, other times it leaves the system hanging and requires a hard shutdown...is this also expected or should I open a new issue?

**Comment by daringer** [comment]
not expected, also not necessarily a firmware only thing, still feel free to create an issue - pls include OS & kernel-version
