### ISSUE TITLE
Cannot change the default kernel

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/heads#5]
In release v1.1 the default kernel cannot be changed for the one lower in the list.
The cause of the bug lies in leaving the other default selection file, which turns up in the sorted list earlier than other positions.

Workaround guide added at:
- https://docs.nitrokey.com/x230/qubes/default-boot.html#changing-default-kernel

**Comment by alex-nitrokey** [comment]
Fixed by c7085d89c3f1b0a3ef36e1937e18ce0792c07247
